apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: navidrome
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
